name: Generate Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Updates daily
  workflow_dispatch:              # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
